

ENERGY_KCAL_ATTRIBUTE_ID = 208
PROTEIN_ATTRIBUTE_ID = 203
CARBOHYDRATE_ATTRIBUTE_ID = 205
FAT_ATTRIBUTE_ID = 204

ATTRIBUTE_ID_LIST = [ENERGY_KCAL_ATTRIBUTE_ID, PROTEIN_ATTRIBUTE_ID, CARBOHYDRATE_ATTRIBUTE_ID, FAT_ATTRIBUTE_ID]